language: python
python: 2.7
env:
  matrix:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py34
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
- travis_wait python -m tox --skip-missing-interpreters -e $TOX_ENV
branches:
  only:
  - master
notifications:
  hipchat: 7d72ba6ba0bf07248f17e0a6a1a899@DevOps
